# Generated by Django 3.2.4 on 2021-09-05 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210905_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='destination',
        ),
        migrations.AddField(
            model_name='ticket',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='main_app.airport'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='origin',
        ),
        migrations.AddField(
            model_name='ticket',
            name='origin',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='origin_airport', to='main_app.airport'),
            preserve_default=False,
        ),
    ]
