# Generated by Django 3.2.4 on 2021-09-05 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210905_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 23, 33, 21, 485220)),
        ),
    ]
