# Generated by Django 3.2.4 on 2021-09-06 01:45

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.CharField(default='01A', max_length=3, validators=[django.core.validators.RegexValidator('^0[1-8][A-D]|09[A-G]|1[0-9][A-G]|[2-3][0-9][A-J]$', code='invalid_seat', message='Please follow the instructions in picking a seat number.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 1, 45, 43, 822212)),
        ),
    ]
